name = Unlimited
description = A simple 3 column layout demonstrating mobile first and Susy.
preview = preview.png
template = unlimited-layout

; Regions
regions[user_bar]       			= User bar
regions[branding]       			= Branding
regions[header]         			= Header
regions[navigation]     			= Navigation bar
regions[overlay]   						= Overlay
regions[hero]     						= Hero
regions[highlighted]    			= Highlighted
regions[help]          				= Help
regions[content]        			= Content
regions[sidebar_first]  			= First sidebar
regions[sidebar_second] 			= Second sidebar
regions[below_content]   			= Below content
regions[above_postscript]   	= Above postscript
regions[postscript_first]   	= Postscript first
regions[postscript_second]   	= Postscript second
regions[postscript_third]   	= Postscript third
regions[postscript_fourth]   	= Postscript fourth
regions[below_postscript]   	= Below postscript
regions[footer]         			= Footer

; Stylesheets
stylesheets[all][] = css/layouts/unlimited/unlimited.layout.css
